let elementsObj = {
    "english":["Hydrogen","Helium","Lithium","Beryllium","Boron","Carbon","Nitrogen","Oxygen","Fluorine","Neon","Sodium","Magnesium","Aluminum","Silicon","Phosphorus","Sulfur","Chlorine","Argon","Potassium","Calcium","Scandium","Titanium","Vanadium","Chromium","Manganese","Iron","Cobalt","Nickel","Copper","Zinc","Gallium","Germanium","Arsenic","Selenium","Bromine","Krypton","Rubidium","Strontium","Yttrium","Zirconium","Niobium","Molybdenum","Technetium","Ruthenium","Rhodium","Palladium","Silver","Cadmium","Indium","Tin","Antimony","Tellurium","Iodine","Xenon","Cesium","Barium","Lanthanum","Cerium","Praseodymium","Neodymium","Promethium","Samarium","Europium","Gadolinium","Terbium","Dysprosium","Holmium","Erbium","Thulium","Ytterbium","Lutetium","Hafnium","Tantalum","Tungsten","Rhenium","Osmium","Iridium","Platinum","Gold","Mercury","Thallium","Lead","Bismuth","Polonium","Astatine","Radon","Francium","Radium","Actinium","Thorium","Protactinium","Uranium","Neptunium","Plutonium","Americium","Curium","Berkelium","Californium","Einsteinium","Fermium","Mendelevium","Nobelium","Lawrencium","Rutherfordium","Dubnium","Seaborgium","Bohrium","Hassium","Meitnerium","Darmstadtium","Roentgenium","Copernicium","Nihonium","Flerovium","Moscovium","Livermorium","Tennessine","Oganesson"],
    "spanish":["Hidrógeno","Helio","Litio","Berilio","Boro","Carbono","Nitrógeno","Oxígeno","Flúor","Neón","Sodio","Magnesio","Aluminio","Silicio","Fósforo","Azufre","Cloro","Argón","Potasio","Calcio","Escandio","Titanio","Vanadio","Cromo","Manganeso","Hierro","Cobalto","Níquel","Cobre","Cinc","Galio","Germanio","Arsénico","Selenio","Bromo","Kriptón","Rubidio","Estroncio","Itrio","Circonio","Niobio","Molibdeno","Tecnecio","Rutenio","Rodio","Paladio","Plata","Cadmio","Indio","Estaño","Antimonio","Telurio","Yodo","Xenón","Cesio","Bario","Lantano","Cerio","Praseodimio","Neodimio","Prometio","Samario","Europio","Gadolinio","Terbio","Disprosio","Holmio","Erbio","Tulio","Iterbio","Lutecio","Hafnio","Tantalio","Tungsteno","Renio","Osmio","Iridio","Platino","Oro","Mercurio","Talio","Plomo","Bismuto","Polonio","Astato","Radón","Francio","Radio","Actinio","Torio","Protactinio","Uranio","Neptunio","Plutonio","Americio","Curio","Berkelio","Californio","Einstenio","Fermio","Mendelevio","Nobelio","Lawrencio","Rutherfordio","Dubnio","Seaborgio","Bohrio","Hassio","Meitnerio","Darmstadtio","Roentgenio","Copernicio","Nihonio","Flerovio","Moscovio","Livermorio","Téneso","Oganesón"],
    "french":["Hydrogène","Hélium","Lithium","Béryllium","Bore","Carbone","Azote","Oxygène","Fluor","Néon","Sodium","Magnésium","Aluminium","Silicium","Phosphore","Soufre","Chlore","Argon","Potassium","Calcium","Scandium","Titane","Vanadium","Chrome","Manganèse","Fer","Cobalt","Nickel","Cuivre","Zinc","Gallium","Germanium","Arsenic","Sélénium","Brome","Krypton","Rubidium","Strontium","Yttrium","Zirconium","Niobium","Molybdène","Technétium","Ruthénium","Rhodium","Palladium","Argent","Cadmium","Indium","Étain","Antimoine","Tellure","Iode","Xénon","Césium","Baryum","Lanthane","Cérium","Praséodyme","Néodyme","Prométhium","Samarium","Europium","Gadolinium","Terbium","Dysprosium","Holmium","Erbium","Thulium","Ytterbium","Lutécium","Hafnium","Tantale","Tungstène","Rhénium","Osmium","Iridium","Platine","Or","Mercure","Thallium","Plomb","Bismuth","Polonium","Astate","Radon","Francium","Radium","Actinium","Thorium","Protactinium","Uranium","Neptunium","Plutonium","Américium","Curium","Berkélium","Californium","Einsteinium","Fermium","Mendélévium","Nobélium","Lawrencium","Rutherfordium","Dubnium","Seaborgium","Bohrium","Hassium","Meitnérium","Darmstadtium","Roentgenium","Copernicium","Nihonium","Flérovium","Moscovium","Livermorium","Tennesse","Oganesson"],
    "german":["Wasserstoff","Helium","Lithium","Beryllium","Bor","Kohlenstoff","Stickstoff","Sauerstoff","Fluor","Neon","Natrium","Magnesium","Aluminium","Silicium","Phosphor","Schwefel","Chlor","Argon","Kalium","Calcium","Scandium","Titan","Vanadium","Chrom","Mangan","Eisen","Cobalt","Nickel","Kupfer","Zink","Gallium","Germanium","Arsen","Selen","Brom","Krypton","Rubidium","Strontium","Yttrium","Zirconium","Niob","Molibdän","Technetium","Ruthenium","Rhodium","Palladium","Silber","Cadmium","Indium","Zinn","Antimon","Tellur","Iod","Xenon","Cäsium","Barium","Lanthan","Cerium","Praseodym","Neodym","Promethium","Samarium","Europium","Gadolinium","Terbium","Dysprosium","Holmium","Erbium","Thulium","Ytterbium","Lutetium","Hafnium","Tantal","Wolfram","Rhenium","Osmium","Iridium","Platin","Oro","Quecksilber","Thallium","Blei","Bismut","Polonium","Astat","Radon","Francium","Radium","Actinium","Thorium","Protactinium","Uran","Neptunium","Plutonium","Americium","Curium","Berkelium","Californium","Einsteinium","Fermium","Mendelevium","Nobelium","Lawrencium","Rutherfordium","Dubnium","Seaborgium","Bohrium","Hassium","Meitnerium","Darmstadtium","Roentgenium","Copernicium","Nihonium","Flerovium","Moscovium","Livermorium","Tenness","Oganesson"],
    "russian":["Водород","Гелий","Литий","Бериллий","Бор","Углерод","Азот","Кислород","Фтор","Неон","Натрий","Магний","Алюминий","Кремний","Фосфор","Сера","Хлор","Аргон","Калий","Кальций","Скандий","Титан","Ванадий","Хром","Марганец","Железо","Кобальт","Никель","Медь","Цинк","Галлий","Германий","Мышьяк","Селен","Бром","Криптон","Рубидий","Стронций","Иттрий","Цирконий","Ниобий","Молибден","Технеций","Рутений","Родий","Палладий","Серебро","Кадмий","Индий","Олово","Сурьма","Теллур","Иод","Ксенон","Цезий","Барий","Лантан","Церий","Празеодим","Неодим","Прометий","Самарий","Европий","Гадолиний","Тербий","Диспрозий","Гольмий","Эрбий","Тулий","Иттербий","Лютеций","Гафний","Тантал","Вольфрам","Рений","Осмий","Иридий","Платина","Золото","Ртуть","Таллий","Свинец","Висмут","Полоний","Астат","Радон","Франций","Радий","Актиний","Торий","Протактиний","Уран","Нептуний","Плутоний","Америций","Кюрий","Берклий","Калифорний","Эйнштейний","Фермий","Менделевий","Нобелий","Лоуренсий","Резерфордий","Дубний","Сиборгий","Борий","Хассий","Мейтнерий","Дармштадтий","Рентгений","Коперниций","Нихоний","Флеровий","Московий","Ливерморий","Теннессин","Оганесон"],
    "chinese":["氫","氦","鋰","鈹","硼","碳","氮","氧","氟","氖","鈉","鎂","鋁","硅","磷","硫","氯","氬","鉀","鈣","鈧","鈦","釩","鉻","錳","鐵","鈷","鎳","銅","鋅","鎵","鍺","砷","硒","溴","氪","銣","鍶","釔","鋯","鈮","鉬","鎝","釕","銠","鈀","銀","鎘","銦","錫","銻","碲","碘","氙","銫","鋇","鑭","鈰","鐠","釹","鉕","釤","銪","釓","鋱","鏑","鈥","鉺","銩","鐿","鑥","鉿","鉭","鎢","錸","鋨","銥","鉑","金","汞","鉈","鉛","鉍","釙","砹","氡","鈁","鐳","錒","釷","鏷","鈾","錼","鈽","銤","鋦","錇","鉲","鑀","鐨","鍆","鍩","鐒","鑪","𨧀","𨭎","𨨏","𨭆","䥑","鐽","錀","鎶","鉨","鈇","鏌","鉝","石田","气奧"],
	"danish":["Hydrogen","Helium","Lithium","Beryllium","Bor","Carbon","Nitrogen","Oxygen","Fluor","Neon","Natrium","Magnesium","Aluminium","Silicium","Fosfor","Svovl","Klor","Argon","Kalium","Calcium","Scandium","Titanium","Vanadium","Krom","Mangan","Jern","Kobolt","Nikkel","Kobber","Zink","Gallium","Germanium","Arsen","Selen","Brom","Krypton","Rubidium","Strontium","Yttrium","Zirkonium","Niobium","Molybdæn","Technetium","Ruthenium","Rhodium","Palledium","Sølv","Cadmium","Indium","Tin","Antimon","Tellur","Jod","Xenon","Cæsium","Barium","Lanthan","Cerium","Praseodym","Neodym","Promethium","Samarium","Europium","Gadolinium","Terbium","Dysprosium","Holmium","Erbium","Thulium","Ytterbium","Lutetium","Hafnium","Tantal","Wolfram","Rhenium","Osmium","Iridium","Platin","Guld","Kviksølv","Thallium","Bly","Bismuth","Polonium","Astat","Radon","Francium","Radium","Actinium","Thorium","Protactinium","Uran","Neptunium","Plutonium","Americium","Curium","Berkelium","Californium","Einsteinium","Fermium","Mendelevium","Nobelium","Lawrencium","Rutherfordium","Dubnium","Seaborgium","Bohrium","Hassium","Meitnerium","Darmstadtium","Roentgenium","Kopernicium","Nihonium","Flerovium","Moscovium","Livermorium","Tennessine","Oganesson"],
	"hindi":["हाइड्रोजन","हिलियम","लिथियम","बेरिलियम","बोरॉन्","कार्बन","नाइट्रोजन","ऑक्सीजन","फ्लोरीन","नियोन","सोडियम","मैग्नेशियम","एल्युमिनियम","सिलिकॉन","फास्फोरस","गन्धक","क्लोरीन","ऑर्गन","पोटैशियम","कैल्शियम","स्काण्डियम","टाइटानियम","वनेडियम","क्रोमियम","मैंगनीज","लोहा","कोबाल्ट","निकेल","ताम्र","जस्ता","गैलियम","जर्मेनियम","आर्सेनिक","सेलेनियम","ब्रोमिन","क्रिप्टन","रुबिडियम","स्ट्रोन्सियम","इत्रियम","जर्कोनियम","नायोबियम","मोलिब्डेनम","टेक्निशियम","रुथेनियम","रोडियम","पलाडियम","चाँदी","काडमियम","इण्डियम","त्रपु","एन्टिमोनी","टेलुरियम","आयोडिन","ज़ेनान","सीज़ियम","बेरियम","लाञ्थनम","सेरियम","प्रासियोडाइमियम","नियोडाइमियम","प्रोमेथियम","सैमरियम","युरोपियम","ग्याडोलिनियम","टर्बियम","डिस्प्रोसियम","होल्मियम","अर्बियम","थुलियम","यिट्टरबियम","लुटेटियम","हाफ्नियम","टाण्टलम","टंग्स्टन","रेनियम","अस्मियम","इरिडियम","प्लाटिनम","सोना","पारा","थैलियम","सीसा","बिस्मथ","पोलोनियम","एस्टाटिन","रेडन","फ्रान्सियम","रेडियम","एक्टिनियम","थोरियम","प्रोटैक्टीनियम","युरेनियम","नेप्ट्यूनियम","प्लूटोनियम","अमेरिशियम","क्यूरियम","बर्केलियम","कैलीफोर्नियम","आइन्स्टाइनियम","फर्मियम","मेण्डेलीवियम","नोबेलियम","लॉरेंशियम","रुथरफोर्डियम","डब्नियम","सीबोर्गियम","बोरियम","हसियम","मेइट्नेरियम","डार्म्स्टेडशियम","रॉन्टजैनियम","उनउनबियम","उनउनट्रियम","उनउनक्वाडृयम","उनउनपैन्शियम","उनउनहैक्षियम","उनउनसैप्क्षियम","उनउनऑक्षियम"],
	"greek":["Ύδρογονο","Ήλιον","Λιθιο","Βηρυλλιο","Βοριο","Ανθρακας","Αζωτο","Οξυγονο","Φθοριο","Νεον","Νατριο","Μαγνησιο","Αργιλιο","Πυριτιο","Φωσφορος","Θειο","Χλωριο","Αργο","Καλιο","Ασβεστιο","Σκανdιο","Τιτανιο","Βαναdιο","Χρωμιο","Μαγγανιο","Σιδηρος","Κοβαλτιο","Νικελιο","Χαλκος","Ψευdαργυρος","Γαλλιο","Γερμανιο","Αρσενικο","Σεληνιο","Βρωμιο","Κρυπτο","Ρουβιdιο","Στροντιο","Υττριο","Ζιρκονιο","Νιοβιο","Μολυβδενιο","Τεχνητιο","Ρουθηνιο","Ροδιο","Παλλαδιο","Αργυρος","Καδμιο","Ινδιο","Κασσιτερος","Αντιμονιο","Τελλουριο","Ιωδιο","Ξενο","Καισιο","Βαριο","Λανθανιο","Δημητριο","Πρασεοδυμιο","Νεοδυμιο","Προμηθειο","Σαμαριο","Ευρωπιο","Γαδολινιο","Τερβιο","Δυσπροσιο","Όλμιο","Ερβιο","Θουλιο","Υττερβιο","Λουτετσιο","Άφνιο","Τανταλιο","Βολφραμιο","Ρηνιο","Οσμιο","Ιριδιο","Λευκοχρυσος","Χρυσος","Ύδραργυρος","Θαλλιο","Μολυβδος","Βισμουθιο","Πολωνιο","Αστατο","Ραδονιο","Φραγκιο","Ραδιο","Ακτινιο","Θοριο","Πρωτακτινιο","Ουρανιο","Ποσeιδωνιο","Πλουτωνιο","Αμερικιο","Κιουριο","Μπερκελιο","Καλιφορνιο","Αινστανιο","Φερμιο","Μεντελεβιο","Νομπελιο","Λωρεντσιο","Ραδερφόρντιο","Ντούμπνιο","Σιμπόργκιο","Μπόριο","Χάσιο","Μαϊτνέριο","Νταρμστάντιο","Ρεντγκένιο","Κοπερνίκιο","Ουνούντριο","Φλερόβιο","Ουνουπέντιο","Λιβερμόριο","Ουνουσέπτιο","Ουνουνόκτιο"],
	"farsi":["هیدروژن","هلیم","لیتیم","بریلیوم","بور","کربن","نیتروژن","اکسیژن","فلوئور","نئون","سدیم","منیزیم","آلومینیم","سیلیسیم","فسفر","گوگرد","کلر","آرگون","پتاسیم","کلسیم","اسکاندیم","تیتانیم","وانادیم","کروم","منگنز","آهن","کبالت","نیکل","مس","روی","گالیم","ژرمانیم","آرسنیک","سلنیم","برم","کریپتون","روبیدیم","استرونسیم","ایتریم","زیرکونیم","نیوبیم","مولیبدن","تکنسیم","رادنیم","رودیم","پالادیم","نقره","کادمیم","ایندیم","قلع","آنتیموان","تلوریم","ید","گزنون","سزیم","باریم","لانتانوم","سریم","پرازئودیمیم","نئودیمیم","پرومتیم","ساماریم","یوروپیم","گادولینیم","تربیم","دیسپروزیم","هولمیم","اربیم","تولیم","ایتربیم","لوتتیم","هافنیم","تانتالوم","تنگستن","رنیم","اوسمیم","ایریدیم","پلاتین","طلا","جیوه","تالیم","سرب","بیسموت","پولونیم","آستاتین","رادون","فرانسیم","رادیم","آکتینیم","توریم","پروتاکتینیم","اورانیم","نپتونیم","پلوتونیم","امریسیم","کوریم","برکلیم","کالیفورنیم","اینشتینیم","فرمیم","مندلیفیم","نوبلیم","لاورنسیم","رادرفوردیم","دابنیم","سیبورگیم","بوریم","هاسیم","میتنریم","دارمشتاتیم","رونتگنیوم","کوپرنیسیم","آن‌ان‌تریوم","فلروویوم","آن‌ان‌پنتیوم","لیورموریوم","آن‌ان‌سپتیوم","آن‌ان‌اکتیوم"],
	"korean":["수소","헬륨","리튬","베릴륨","붕소","탄소","질소","산소","플루오르","네온","나트륨","마그네슘","알루미늄","규소","인","황","염소","아르곤","칼륨","칼슘","스칸듐","타이타늄","바나듐","크롬","망간","철","코발트","니켈","구리","아연","갈륨","게르마늄","비소","셀렌","브롬","크립톤","루비듐","스트논듐","이트륨","지르코늄","나이오븀","몰리브덴","테크네튬","루테늄","로듐","팔라듐","은","카드뮴","인듐","주석","안티몬","텔루르","요오드","크세논","세슘","바륨","란탄","세륨","프라세오디뮴","네오디뮴","프로메튬","사마륨","유로퓸","가돌리늄","테르븀","디스프로슘","홀뮴","에르븀","툴륨","이테르븀","루테튬","하프늄","탄탈","텅스텐","레늄","오스뮴","이리듐","백금","금","수은","탈륨","납","비스무트","폴로늄","아스타틴","라돈","프랑슘","라듐","악티늄","토륨","프로트악티늄","우라늄","넵투늄","플루토늄","아메리슘","퀴륨","버클륨","칼리포르늄","아인시타이늄","페르뮴","멘델레븀","노벨륨","로렌슘","러더포듐","더브늄","새보쥼","보륨","하슘","마이트너륨","다름슈타튬","뢴트게늄","코페르니슘","우눈트륨","플레로븀","우눈펜튬","리버모륨","우눈셉튬","우누녹튬"],
	"polish":["Wodór","Hel","Lit","Beryl","Bor","Węgiel","Azot","Tlen","Fluor","Neon","Sód","Magnez","Glin","Krzem","Fosfor","Siarka","Chlor","Argon","Potas","Wapń","Skand","Tytan","Wanad","Chrom","Mangan","Żelazo","Kobalt","Nikiel","Miedź","Cynk","Gal","German","Arsen","Selen","Brom","Krypton","Rubid","Stront","Itr","Cyrkon","Niob","Molibden","Technet","Ruten","Rod","Pallad","Srebro","Kadm","Ind","Cyna","Antymon","Tellur","Jod","Ksenon","Cez","Bar","Lantan","Cer","Prazeodym","Neodym","Promet","Samar","Europ","Gadolin","Terb","Dyspoz","Holm","Erb","Tul","Iterb","Lutet","Hafn","Tantal","Wolfram","Ren","Osm","Iryd","Platyna","Złoto","Rtęć","Tal","Ołów","Bizmut","Polon","Astat","Radon","Frans","Rad","Aktyn","Tor","Proaktyn","Uran","Neptun","Pluton","Ameryk","Kiur","Bekerel","Kaliforn","Einstein","Ferm","Mendelew","Nobel","Lorens","Rutherford","Dubn","Seaborg","Bohr","Has","Meitner","Darmsztadt","Roentgen","Kopernik","Nihonium","Flerovium","Moscovium","Livermorium","Tennessine","Oganesson"],
	"Portuguese":["Hidrogéno","Hélio","Lítio","Berílio","Boro","Carbono","Nitrogénio","Oxigénio","Flúor","Néon","Sódio","Magnésio","Alumínio","Silício","Fósforo","Enxofre","Cloro","Argon","Potássio","Cálcio","Escândio","Titânio","Vanádio","Crómo","Manganésio","Ferro","Cobalto","Níquel","Cobre","Zinco","Gálio","Germânio","Arsénic","Selénio","Bromo","Krípton","Rubídio","Estrôncio","Itrio","Zircónio","Nióbio","Molibdénio","Tecnécio","Ruténio","Ródio","Paládio","Prata","Cádmio","Índio","Estanho","Antimónio","Telúrio","Iodo","Xénon","Césio","Bário","Lantâno","Cério","Praseodímio","Neodímio","Promécio","Samário","Európio","Gadolínio","Térbio","Disprósio","Hólmio","Érbio","Túlio","Itérbio","Lutécio","Háfnio","Tântalo","Tungsténio","Rénio","Ósmio","Irídio","Platina","Ouro","Mercúrio","Tálio","Chumbo","Bismuto","Polónio","Astato","Rádon","Frâncio","Rádio","Actínio","Tório","Protacnídio","Urânio","Neptúnio","Plutónio","Amerício","Cúrio","Berqueélio","Califórnio","Einstânio","Férmio","Mendelévio","Nobélio","Lawrêncio","Rutherfórdio","Dúbnio","Seabórgio","Bóhrio","Hássio","Meitnério","Darmstádio","Roentgênio","Copernício","Nihonium","Fleróvio","Moscovio","Livermório","Tennessine","Oganesson"]
};

let groups = {
    "english":["Alkali Metals","Alkaline Earth Metals","Lanthanoids","Actinides","Transition Metals","Post-Transition Metals","Metalloids","Other Nonmetals","Noble Gases","Unknown"],
    "spanish":["Metales Alcalinos","Metales Alcalinos Térreos","Lantánidos","Actínidos","Metales de Transición","Metales Pobres","Metaloides","No Metales","Gases Nobles","Desconocido"],
    "french":["Métal Alcalin","Alcalino-terreux","Lanthanide","Actinide","Métal de Transition","Post-Transition Metals","Metalloids","Other Nonmetals","Gaz Noble","Inconnue"],
    "german":["Alkalimetalle","Erdalkalimetalle","Lanthanoide","Actinoide","Übergangsmetalle","Metalle","Halbmetalle","Nichtmetalle","Edelgase","Unbekannt"],
    "russian":["Щелочные металлы","Щёлочноземельные металлы","Лантаноиды","Актиноиды","Переходные металлы","Post-Transition Metals","Metalloids","Other Nonmetals","Благородные газы","Неизвестно"],
    "chinese":["碱金属","碱土金属","镧系元素","锕系元素","过渡金属","后过渡金属","准金属","其他非金属","稀有气体","未知"],
	"danish":["Alkalimetaller","Alkaliske Jordmetaller","Lantanider","Actinider","Overgangsmetaller","Andre metaller","Metalloider","Ikke metaller","Ædle Gasser","Ukendt"],
	"hindi":["क्षारीय धातु","क्षारीय पृथ्वी धातु","Lanthanoids","एक्टिनाइड्स","संक्रमण धातुओं","संक्रमण के बाद की धातुएँ","Metalloids","अन्य अधातु","उत्कृष्ट गैस","अनजान"],
	"greek":["Αλκαλι μέταλλα","Μέταλλα αλκαλικής γης","Λανθάνης","Ακτινίδες","Μεταβατικά Μέταλλα","Μέταλλα μετά τη μετάβαση","Μεταλλοειδή","Άλλα μη μέταλλα","Ευγενή αέρια","Αγνωστος"],
	"farsi":["فلزات قلیایی","فلزات قلیایی زمینی","لانتانوئیدها","اکتینیدها","فلزات واسطه","فلزات پس از انتقال","فلزات","غیر فلزات دیگر","گازهای نجیب","ناشناس"],
	"korean":["알칼리 금속","알칼리 토금속","란타 노이드","악티늄 족","전이 금속","전이 후 금속","메탈 로이드","기타 비금속","고귀한 가스","알 수 없는"],
	"polish":["Metale alkaliczne","Metale ziem alkalicznych","Lantanowce","Aktynowce","Metale przejściowe","Post-Transition Metals","Metaloidy","Inne niemetale","Gazy szlachetne","Nieznany"],
	"Portuguese":["Metais Alcalinos","Metais Alcalino-terrosos","Lantanoides","Actinídeos","Metais de Transição","Metais Representativos","Semimetais","Não Metais","Gases Nobres","Desconhecidos"]
}

let SETTINGS = {
    LANGUAGE:"english",
    BACKGROUND_COLOR: { r: 0.06, g: 0.07, b: 0.09 } // "#101318"
}

function getLanguage(value){
   let allElements = document.getElementsByClassName("name");
   let len = eval(`elementsObj.${value}.length;`);

   for(let i=0; i<len; i++){
       allElements[i].innerHTML = eval(`elementsObj.${value}[${i}];`)
   }

   let theGroups = document.getElementsByClassName("group");
   len = eval(`groups.${value}.length;`);

   for(let i=0; i<len; i++){
    theGroups[i].innerHTML = eval(`groups.${value}[${i}];`)
	}

}

document.addEventListener("DOMContentLoaded", () => {   
    window.wallpaperPropertyListener = {
        applyUserProperties: (properties) => {
			if (properties.background_color) {
                let s = properties.background_color.value.split(" "),
                b_r = Math.floor(s[0]*255),
                b_g = Math.floor(s[1]*255),
                b_b = Math.floor(s[2]*255);
                document.body.style.backgroundColor = `rgb(${b_r}, ${b_g}, ${b_b})`;
                SETTINGS.BACKGROUND_COLOR.r = b_r;
                SETTINGS.BACKGROUND_COLOR.g = b_g;
                SETTINGS.BACKGROUND_COLOR.b = b_b;
            }
			if (properties.language) {
				SETTINGS.LANGUAGE = properties.language.value;
				getLanguage(SETTINGS.LANGUAGE);
			}
		}
    };
});